// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable enable
using System;
using System.Collections.Generic;
using OfficeBookingWeb.Domain.Common;

namespace OfficeBookingWeb.Domain.Entities;

public partial class Car : AuditableEntity
{
    public int CarId { get; set; }

    public int EmployeeId { get; set; }

    public string CarBrand { get; set; } = null!;

    public string RegisterNumber { get; set; } = null!;

    public virtual Employee Employee { get; set; } = null!;
}