// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using OfficeBookingWeb.Domain.Common;
using System;
using System.Collections.Generic;

namespace OfficeBookingWeb.Domain.Entities;

public partial class Department : AuditableEntity
{
    public int DepartmentId { get; set; }

    public string DepartmentName { get; set; }

    public virtual ICollection<Employee> Employees { get; set; } = new List<Employee>();
}