// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using OfficeBookingWeb.Domain.Common;
using System;
using System.Collections.Generic;

namespace OfficeBookingWeb.Domain.Entities;

public partial class Employee : AuditableEntity
{
    public int EmployeeId { get; set; }

    public string FullName { get; set; }

    public int? DepartmentId { get; set; }

    public virtual ICollection<Car> Cars { get; set; } = new List<Car>();

    public virtual Department Department { get; set; }

    public virtual ICollection<OfficePresence> OfficePresences { get; set; } = new List<OfficePresence>();

    public virtual ICollection<ParkingReservation> ParkingReservations { get; set; } = new List<ParkingReservation>();
}