// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable enable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using OfficeBookingWeb.Domain.Common;

namespace OfficeBookingWeb.Domain.Entities;

public partial class OfficePresence : AuditableEntity
{
    public int PresenceId { get; set; }

    public DateOnly PresenceDate { get; set; }

    public int EmployeeId { get; set; }

    public int? ReservationId { get; set; }

    public int RoomId { get; set; }

    public string? Notes { get; set; }

    public virtual Employee Employee { get; set; } = null!;

    public virtual ParkingReservation? ParkingReservation { get; set; }

    public virtual OfficeRoom Room { get; set; } = null!;
}