// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using OfficeBookingWeb.Domain.Common;
using System;
using System.Collections.Generic;

namespace OfficeBookingWeb.Domain.Entities;

public partial class OfficeRoom : AuditableEntity
{
    public int RoomId { get; set; }

    public string RoomNumber { get; set; }

    public int RoomCapacity { get; set; }

    public virtual ICollection<OfficePresence> OfficePresences { get; set; } = new List<OfficePresence>();
}