// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable enable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using OfficeBookingWeb.Domain.Common;

namespace OfficeBookingWeb.Domain.Entities;

public partial class OfficeRoom : AuditableEntity
{
    [Key]
    public int RoomId { get; set; }

    public string RoomNumber { get; set; } = null!;

    public int RoomCapacity { get; set; }

    public virtual ICollection<OfficePresence> OfficePresences { get; set; } = new List<OfficePresence>();
}