// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using OfficeBookingWeb.Domain.Common;
using System;
using System.Collections.Generic;

namespace OfficeBookingWeb.Domain.Entities;

public class OfficePresence : AuditableEntity
{
    public int PresenceId { get; set; }

    public DateOnly PresenceDate { get; set; }

    public int EmployeeId { get; set; }

    public int? ReservationId { get; set; }

    public int RoomId { get; set; }

    public string? Notes { get; set; }

    public virtual Employee Employee { get; set; }

    public virtual ParkingReservation Reservation { get; set; }

    public virtual OfficeRoom Room { get; set; }
}