// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using OfficeBookingWeb.Domain.Common;
using System;
using System.Collections.Generic;

namespace OfficeBookingWeb.Domain.Entities;

public partial class ParkingReservation : AuditableEntity
{
    public int ReservationId { get; set; }

    public int EmployeeId { get; set; }

    public int ParkingSpotId { get; set; }

    public DateOnly ArrivalTime { get; set; }

    public DateOnly DepartureTime { get; set; }

    public virtual Employee Employee { get; set; }

    public virtual ICollection<OfficePresence> OfficePresences { get; set; } = new List<OfficePresence>();

    public virtual ParkingSpot ParkingSpot { get; set; }
}