// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable enable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using OfficeBookingWeb.Domain.Common;

namespace OfficeBookingWeb.Domain.Entities;

public partial class ParkingReservation : AuditableEntity
{
    public int ReservationId { get; set; }

    public int EmployeeId { get; set; }

    public int ParkingSpotId { get; set; }

    public DateTime? ArrivalTime { get; set; }

    public DateTime? DepartureTime { get; set; }

    public virtual Employee Employee { get; set; } = null!;

    public virtual ICollection<OfficePresence> OfficePresences { get; set; } = new List<OfficePresence>();

    public virtual ParkingSpot ParkingSpot { get; set; } = null!;
}